-- ---------------------------------------------------------------------------
-- V1: patient table, PID sequence and the indexes that support the grid.
--
-- The schema is owned by Flyway, not by Hibernate's ddl-auto. Generated DDL is
-- fine for a demo and unusable in production: it cannot express a rename, it
-- gives no change-control point for indexes, and it differs between Hibernate
-- versions. Writing the migration by hand costs a few minutes and makes the
-- schema an explicit, repeatable artefact.
-- ---------------------------------------------------------------------------

CREATE SEQUENCE patient_pid_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE patient (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Business identity. UNIQUE is the constraint that actually guarantees no two
    -- patients share a PID; the application level sequence only avoids collisions
    -- in the happy path.
    pid           VARCHAR(20)  NOT NULL,

    first_name    VARCHAR(60)  NOT NULL,
    last_name     VARCHAR(60)  NOT NULL,
    date_of_birth DATE         NOT NULL,
    gender        VARCHAR(10)  NOT NULL,

    -- Normalised to E.164 (+61XXXXXXXXX) by the application before it gets here.
    phone_no      VARCHAR(20)  NOT NULL,

    street        VARCHAR(200) NOT NULL,
    suburb        VARCHAR(100) NOT NULL,
    state         VARCHAR(3)   NOT NULL,
    postcode      VARCHAR(4)   NOT NULL,

    -- Optimistic locking token, maintained by JPA @Version.
    version       BIGINT       NOT NULL DEFAULT 0,

    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,

    CONSTRAINT uk_patient_pid        UNIQUE (pid),
    CONSTRAINT ck_patient_gender     CHECK (gender IN ('MALE', 'FEMALE', 'OTHER', 'UNKNOWN')),
    CONSTRAINT ck_patient_state      CHECK (state IN ('ACT', 'NSW', 'NT', 'QLD', 'SA', 'TAS', 'VIC', 'WA')),
    CONSTRAINT ck_patient_postcode   CHECK (LENGTH(postcode) = 4)
    -- No CHECK on date_of_birth: it would have to reference CURRENT_DATE, which is
    -- not immutable, so PostgreSQL rejects it and other engines would only evaluate
    -- it at write time anyway. "Must be in the past" is enforced by @Past instead.
);

-- Default grid ordering is (last_name, first_name); a composite index lets the
-- database satisfy the ORDER BY from the index instead of sorting every page.
CREATE INDEX ix_patient_name ON patient (last_name, first_name);

-- Supports sorting and any future "patients born between" reporting query.
CREATE INDEX ix_patient_dob ON patient (date_of_birth);

-- Search is a case insensitive LIKE across pid/first_name/last_name. The index
-- that would actually serve it is a lower-cased expression index:
--
--     CREATE INDEX ix_patient_last_name_lower ON patient (LOWER(last_name));
--
-- H2 (the database this assessment ships with) does not support expression
-- indexes, so it is deliberately left out here rather than added in a form that
-- only works on one engine. On PostgreSQL the two statements above belong in a
-- follow-up migration, together with a pg_trgm GIN index for the leading
-- wildcard case. See "Search and indexing" in the README.

-- PID lookups (GET /patients/by-pid/{pid}) are already served by uk_patient_pid.
